version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=adminpassword
      # Set up file storage so n8n and python container can share files
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared:/data

  python:
    image: python:3.11
    container_name: mypython
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./shared:/data
    working_dir: /data
    command: >
      bash -c "pip install --upgrade pip &&
               pip install -r /requirements.txt &&
               tail -f /dev/null"
    # Optionally, expose a port if you run a service like Jupyter or FastAPI
    # ports:
    #   - "8888:8888"

volumes:
  n8n_data:
